### ISSUE TITLE
Getting an exception while using the plug-in

### ISSUE THREAD

**Issue by dinkame** [tgrosinger/recent-files-obsidian#98]
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'redraw')
    at M.handleDelete (plugin:recent-files-obsidian:6:7385)
    at e.tryTrigger (app.js:1:722881)
    at e.trigger (app.js:1:722814)
    at t.trigger (app.js:1:740919)
    at t.onChange (app.js:1:731345)
    at e.trigger (app.js:1:545440)
    at e.removeFile (app.js:1:546253)
    at e.<anonymous> (app.js:1:545358)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at app.js:1:236249
    at new Promise (<anonymous>)
    at v (app.js:1:235994)
    at e.reconcileDeletion (app.js:1:544960)
    at e.<anonymous> (app.js:1:542051)
    at app.js:1:237228
    at Object.next (app.js:1:237333)
    at a (app.js:1:236051)

**Comment by tgrosinger** [comment]
Hello,
Could you please provide some more details about what actions led to this exception so we can better narrow down the cause? Thank you.

**Comment by tgrosinger** [comment]
Please make sure you update to the latest version of the extension and Obsidian. If you continue encountering this issue please reopen this and provide some additional details about how to recreate the issue. Thank you.
